### ISSUE TITLE
How to install simulator on ubuntu 20

### ISSUE THREAD

**Issue by AlirezaGhanavati** [HighW4y2H3ll/OCTEON-im8724-SDK#2]
Hi everyone!
How do I install the simulator on ubuntu 20?
Thanks

**Comment by HighW4y2H3ll** [comment]
I don't have the simulator either! I'd suggest contact your vendor for the info?
Please let me know if you got any luck! Thank you!

**Comment by AlirezaGhanavati** [comment]
Hi again!
First of all, how do I install the SDK?
According to the README file, an rpm file must exist, but I can't find it. 
In the next step, according to existing docs, to execute the simulator we have to run the following command in examples/hello dir:
make run
or
oct-sim hello -quiet
After executing the command, The result should be something like this:
` PP0:~CONSOLE-> Hello world!`
But I achieved something like this:
`oct-sim hello -quit        //next rows:
No -memsize argument provided, using default: 384,256,256,256 Megabytes
memsize=384,256,256,256
node#0: mem size is 384 Megabytes
Using simulator: cn68xx-simulator64
Loading hello to boot bus address 0x1000000
Starting simulator....
Executing command: cn68xx-simulator64 -ld=0x10000000:hello -ld=0x1ffffff0:0x8 -ld=0x0:0x10000000 -ld=0x20000000:0x8000000 -ld=0x1ffffff8:/tmp/C1CIGR6ZPP -ld=0x1fffffd0:/tmp/zVG_C_JxYf -ld=0x1fe00000:0x1000 -ld=0x100001D020000:0x10 -modes=fastboot,pass2, -ld=0x1fc00000:0x40000 -ld=0x1fc00000:/home/rooney/octeon/OCTEON-SDK-5.1/OCTEON-SDK/target/bin/u-boot-octeon_sim.bin /home/rooney/octeon/OCTEON-SDK-5.1/OCTEON-SDK/target/bin/sim-magic-elf -quit
`
You can cure my headache with these tips!
Thank you for your patience!

**Comment by HighW4y2H3ll** [comment]
yeah, I don't have the emulator either. The soft link towards `simulator/bin` is empty.
I think the chip datasheet is bounded to NDA, and different board manufactures probably have their custom QEMU build.
My best guess is to ask your distributor if there's any luck.
Please keep me posted! Thank you & good luck!

**Comment by AlirezaGhanavati** [comment]
> yeah, I don't have the emulator either. The soft link towards `simulator/bin` is empty.
> I think the chip datasheet is bounded to NDA, and different board manufactures probably have their custom QEMU build.
> My best guess is to ask your distributor if there's any luck.
> Please keep me posted! Thank you & good luck!

Thanks for the reply!
 But do you have any idea about the lack of the rpm file?

**Comment by AlirezaGhanavati** [comment]
Hi again
As you mentioned, although there are shortcuts in the `host/bin` , the bin files are not available in the `simulator/bin` .
Is there no way to build simulator binaries?
I know I passed on my headache to you!
Wish you the best.
![image](https://user-images.githubusercontent.com/80429577/110965787-c8498c00-8369-11eb-9ebf-15b60a985314.png)

**Comment by FlorianHeigl** [comment]
Hi guys, for the record, there's a repo with a KVM patchset that allows to emulate an Octeon CPUI, some day someone might be able to use that as a plug-in replacement for the Octeon SIM. I don't know if the things like PCI console would work and I doubt attaching EJTAG would work, but at least there's some general options open to who wants to try running _some_ of the simulator features.

Links: Original https://github.com/amir-mehmood/QEMU-Octeon-MIPS64 that was a research project, there's a papoer to read also.
Improved version: https://github.com/retu2libc/QEMU-Octeon-MIPS64 this is from someone who found the prior and wanted to make it better

I recommend reading the paper for the first 
M. A. Mehmood, Q. U. Ain, A. Akram, A. Qadeer and A. Waheed, "Emulating an Octeon MIPS64 based embedded system on X86 in QEMU," 2016 19th International Multi-Topic Conference (INMIC), Islamabad, 2016, pp. 1-7
And to use the software from the second

And if you do that and plug it in for the octeon sim, for the love of everything, **please post** about it!
