### ISSUE TITLE
git-lfs objects - bandwidth limits...

### ISSUE THREAD

**Issue by neggles** [HighW4y2H3ll/OCTEON-im8724-SDK#3]
Hey, so I'm attempting to fork this repo to do some Shenanigans™ with an Ubiquiti USG-XG-8 (aka "silver edgerouter infinity with an LCD) and there's a couple of git-lfs files that I'm not able to pull down thanks to GitHub's LFS policies being... well frankly ridiculous.

the files in question are `linux/debian/debian_octeon-jessie.tgz` and `ejtag/windriver-ice2/windriver-ejtag-cn73xx.dtl` - the second one I don't much care about, though.

[GitHub's LFS billing policy](https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/about-billing-for-git-large-file-storage) here is immensely unfriendly; when you fork a repo, the original repo owner gets charged bandwidth for all the LFS objects in the repo - even though GitHub doesn't actually have to copy anything to make a fork??? - and just to make things worse, downloading an LFS object from the fork *also* charges the original root repository *even if you're several forks down the tree.*

The only way around that seems to be mirroring the repo rather than forking it - I went to go and do that, but as a result of me having forked Hurricos' fork of this repo you've run out of LFS bandwidth for this month, so I can't download that tarball.

Yay.

I don't suppose you'd have a local copy you could upload somewhere? Very sorry for the trouble. Why GitHub can't/won't add a "charge me for LFS downloads from this fork" button is beyond me...

**Comment by HighW4y2H3ll** [comment]
Yes... that sucks. I've uploaded these files. Please checkout `releases/tag/lfs-mirror`
