### ISSUE TITLE
how to setup the hardware OCTEON CN2350 SmartNIC?

### ISSUE THREAD

**Issue by hailongeric** [HighW4y2H3ll/OCTEON-im8724-SDK#4]
I borrowed the OCTEON CN2350 SmartNIC. And I have nothing about the user's guide and SDK. I am pleased that @Hurricos @HighW4y2H3ll shared this SDK. But I don't know how to activate SmartNIC using u_boot and bootloader according to this SDK?

**Comment by Hurricos** [comment]
*borrowed*?

Can you share photos?

You may want to also see
https://forum.openwrt.org/t/wip-porting-openwrt-to-cavium-cn6640-snic10e-octeon-ii-nic/88461
.


Martin

**Comment by hailongeric** [comment]
Thank you very much!

Yes,  I got it from my friend that he bought it from the secondary market.

I run command "lshw" and it prints:

description: Ethernet interface
                product: CN23XX [LiquidIO II] Intelligent Adapter
                vendor: Cavium, Inc.
                physical id: 0
                bus info: pci@0000:01:00.0
                logical name: enp1s0f0
                version: 02
                serial: 00:0f:b7:30:0d:bc
                capacity: 10Gbit/s
                width: 64 bits
                clock: 33MHz
                capabilities: bus_master cap_list rom ethernet physical fibre 10000bt-fd
                configuration: autonegotiation=off broadcast=yes driver=liquidio firmware=1.7.2 ip=192.168.101.6 latency=0 link=no multicast=yes port=fibre
                resources: irq:16 memory:b4000000-b47fffff memory:ac000000-afffffff memory:b5000000-b50fffff memory:ab310000-ab31ffff memory:b5100000-b90fffff

Some tools in SDK are rebuilt by me and it works normally.  Because oct-remote-boot worked wrong before.   And now I will build u-boot for CN2350.

**Comment by FlorianHeigl** [comment]
@hailongeric could you make a PR with your changes or anything? I have the same card and am not able to figure out what is going wrong, but sure enough I can't really load things.
