### ISSUE TITLE
make kernel error: tlbmiss_handler_setup_pgd undefined

### ISSUE THREAD

**Issue by hailongeric** [HighW4y2H3ll/OCTEON-im8724-SDK#5]
I run 'make kernel' in linux directory. I use all default configs. But there are some errors.

arch/mips/vdso/Makefile:30: MIPS VDSO requires binutils >= 2.25
  Building modules, stage 2.
  MODPOST 27 modules
ERROR: "init_mm" [arch/mips/kvm/kvm.ko] undefined!
ERROR: "tlbmiss_handler_setup_pgd" [arch/mips/kvm/kvm.ko] undefined!
ERROR: "pmd_init" [arch/mips/kvm/kvm.ko] undefined!
ERROR: "__flush_cache_all" [arch/mips/kvm/kvm.ko] undefined!
ERROR: "pgd_init" [arch/mips/kvm/kvm.ko] undefined!
ERROR: "invalid_pmd_table" [arch/mips/kvm/kvm.ko] undefined!
make[3]: *** [scripts/Makefile.modpost:91: __modpost] Error 1
make[2]: *** [Makefile:1201: modules] Error 2
make[2]: Leaving directory '/home/eric/OCTEON-im8724-SDK/linux/kernel/linux'
make[1]: *** [Makefile:11: linux] Error 2
make[1]: Leaving directory '/home/eric/OCTEON-im8724-SDK/linux/kernel'
make: *** [Makefile:130: kernel-deb] Error 2

I don't find those functions' definitions and I don't know how to set up those functions. I google those errors and no solution is found by me.

**Comment by HighW4y2H3ll** [comment]
ah, yes, I was playing around with kvm back then, and I ported a 5.4 kvm module to this 4.9 kernel. Are you currently on the main branch? You could probably :
1. disable Virtualization/KVM build if you don't really need it.
2. Or revert back to commit 600760d2df274d40ac98808be8d682bf829ecb90 before 5.4 kvm code was introduced.
3. Or maybe try the dev_kvm branch where I've made some workaround.
